<a href="https://colab.research.google.com/github/Abilash-Alugonda/Python--course/blob/main/Day36.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy


In [ ]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
print("1-dim",arr1,sep='\n',end ="\n\n")
arr2 = np.array([[1,2,3],[4,5,6]])
print("2-dim",arr2,sep='\n',end ='\n\n')



1-dim
[1 2 3 4 5]

2-dim
[[1 2 3]
 [4 5 6]]



In [ ]:
zeros = np.zeros((3,4))
print(zeros)
ones =np.ones((3,4))
print(ones)
identity = np.eye(4)
print(identity)
full_array = np.full((10,2),20)
print(full_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[20 20]
 [20 20]
 [20 20]
 [20 20]
 [20 20]
 [20 20]
 [20 20]
 [20 20]
 [20 20]
 [20 20]]
